# Etapa D (sesiones 14-15): Prometheus + Grafana + exportador de lag.
# El agente JMX Exporter convierte las métricas JMX en HTTP /metrics en 9101-9103.
# Prometheus: http://localhost:9090 · Grafana: http://localhost:3000 (admin/admin)
services:
  broker1:
    environment:
      KAFKA_OPTS: "-javaagent:/opt/jmx/jmx_prometheus_javaagent-1.6.0.jar=9101:/opt/jmx/kafka.yml"
    volumes:
      - ./jmx:/opt/jmx:ro

  broker2:
    environment:
      KAFKA_OPTS: "-javaagent:/opt/jmx/jmx_prometheus_javaagent-1.6.0.jar=9102:/opt/jmx/kafka.yml"
    volumes:
      - ./jmx:/opt/jmx:ro

  broker3:
    environment:
      KAFKA_OPTS: "-javaagent:/opt/jmx/jmx_prometheus_javaagent-1.6.0.jar=9103:/opt/jmx/kafka.yml"
    volumes:
      - ./jmx:/opt/jmx:ro

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.9.0
    container_name: kafka-exporter
    ports: ["9308:9308"]
    command: ["--kafka.server=broker1:19092", "--kafka.server=broker2:19092", "--kafka.server=broker3:19092"]
    # Exporta el consumer lag DESDE FUERA de la aplicación consumidora (sesión 14)

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alertas.yml:/etc/prometheus/alertas.yml:ro

  grafana:
    image: grafana/grafana:11.0.11
    container_name: grafana
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/tablero-referencia.json:/var/lib/grafana/dashboards/tablero-referencia.json:ro

volumes:
  grafanadata:
